### ISSUE TITLE
the uImage can't be removed when make clean

### ISSUE THREAD

**Issue by njliang** [PeterOgden/PYNQ_image#1]
refer to  your project,  i setup a project which only produce BOOT.bin and kernel image.
when i make clean the project,  the uImage located in linux-xlnx/arc/arm/boot can't be removed. 

but when i am in linux-xlnx folder,  the uImage will be removed normally when i input make clean.
WHY?

**Comment by PeterOgden** [comment]
Hello

This repository has been deprecated and all of its functionality moved into the main PYNQ repo in the `sd_build` directory. Hopefully that will sort out most of your problems. This version is known to contain a number of issues which we've been working on fixing over there.

**Comment by njliang** [comment]
got it
